name: Release

on:
  release:
    types: [published, created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get tag
      id: tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi

    - name: Get version  
      id: version
      run: |
        VERSION=$(echo "${{ steps.tag.outputs.tag }}" | sed 's/^v//')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

  build:
    name: Build Windows x64
    runs-on: windows-latest
    needs: [prepare]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: |
        cargo build --release --target x86_64-pc-windows-msvc --verbose
        
    - name: Verify build
      run: |
        if (!(Test-Path "target\x86_64-pc-windows-msvc\release\rs_fast_image_viewer.exe")) {
          Write-Error "Build failed: Executable not found"
          exit 1
        }
        $size = (Get-Item "target\x86_64-pc-windows-msvc\release\rs_fast_image_viewer.exe").Length
        Write-Host "Build successful. Executable size: $size bytes"

    - name: Create sample config file
      run: |
        @"
        # rs_fast_image_viewer 設定ファイル
        # 最小ウィンドウサイズ (幅, 高さ)
        min_window_size = [800, 600]
        
        # ソートアルゴリズム
        # "FileName"    - ファイル名でソート
        # "CreatedTime" - 作成日時でソート  
        # "ModifiedTime"- 更新日時でソート
        sort_algorithm = "FileName"
        "@ | Out-File -FilePath "rs_fast_image_viewer.toml" -Encoding UTF8

    - name: Create README for release
      run: |
        @"
        # rs_fast_image_viewer ${{ needs.prepare.outputs.version }}
        
        WebP対応の高速画像ビューアー (Windows x64)
        
        ## 使用方法
        
        \`\`\`
        rs_fast_image_viewer.exe [画像ファイルまたはディレクトリ]
        \`\`\`
        
        ## キーボードショートカット
        
        - → または X: 次の画像
        - ← または Z: 前の画像  
        - Enter または Escape: 終了
        
        ## 設定
        
        同じディレクトリの rs_fast_image_viewer.toml で設定を変更できます。
        
        ## システム要件
        
        - Windows 10/11 (64bit)
        - DirectX 12, Vulkan, またはOpenGL ES対応GPU
        
        ## 対応フォーマット
        
        - JPEG (.jpg, .jpeg)
        - PNG (.png)
        - WebP (.webp)
        
        詳細な情報: https://github.com/${{ github.repository }}
        "@ | Out-File -FilePath "README-release.md" -Encoding UTF8

    - name: Prepare release directory
      run: |
        $releaseDir = "rs_fast_image_viewer-windows-x64"
        New-Item -ItemType Directory -Force -Path $releaseDir
        
        # Copy executable
        Copy-Item "target\x86_64-pc-windows-msvc\release\rs_fast_image_viewer.exe" "$releaseDir\"
        
        # Copy config file
        Copy-Item "rs_fast_image_viewer.toml" "$releaseDir\"
        
        # Copy README
        Copy-Item "README-release.md" "$releaseDir\README.md"
        
        # Copy LICENSE if exists
        if (Test-Path "LICENSE") {
          Copy-Item "LICENSE" "$releaseDir\"
        }
        
        # Create version info
        @"
        rs_fast_image_viewer ${{ needs.prepare.outputs.version }}
        Target: x86_64-pc-windows-msvc
        Built: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')
        Commit: ${{ github.sha }}
        "@ | Out-File -FilePath "$releaseDir\VERSION.txt" -Encoding UTF8

    - name: Create ZIP archive
      run: |
        Compress-Archive -Path "rs_fast_image_viewer-windows-x64" -DestinationPath "rs_fast_image_viewer-windows-x64.zip" -CompressionLevel Optimal

    - name: Create checksum
      run: |
        $hash = Get-FileHash "rs_fast_image_viewer-windows-x64.zip" -Algorithm SHA256
        "$($hash.Hash.ToLower())  rs_fast_image_viewer-windows-x64.zip" | Out-File -FilePath "rs_fast_image_viewer-windows-x64.zip.sha256" -Encoding ASCII

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rs_fast_image_viewer-windows-x64
        path: |
          rs_fast_image_viewer-windows-x64.zip
          rs_fast_image_viewer-windows-x64.zip.sha256
        
    - name: Upload executable separately
      uses: actions/upload-artifact@v4
      with:
        name: rs_fast_image_viewer-exe
        path: target/x86_64-pc-windows-msvc/release/rs_fast_image_viewer.exe

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: github.event_name == 'release'
    permissions:
      contents: write
    
    steps:
    - name: Download ZIP artifacts
      uses: actions/download-artifact@v4
      with:
        name: rs_fast_image_viewer-windows-x64
        path: artifacts

    - name: Download executable artifact
      uses: actions/download-artifact@v4
      with:
        name: rs_fast_image_viewer-exe
        path: artifacts

    - name: Display structure
      run: find artifacts -type f -name "*" | sort

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/rs_fast_image_viewer-windows-x64.zip
          artifacts/rs_fast_image_viewer-windows-x64.zip.sha256
          artifacts/rs_fast_image_viewer.exe
        name: "rs_fast_image_viewer ${{ needs.prepare.outputs.version }}"
        body: |
          ## rs_fast_image_viewer ${{ needs.prepare.outputs.version }}
          
          WebP対応の高速画像ビューアーです。
          
          ### ダウンロード
          
          **推奨:** `rs_fast_image_viewer-windows-x64.zip` - 設定ファイル付きの完全パッケージ
          
          または、実行ファイルのみ: `rs_fast_image_viewer.exe`
          
          ### システム要件
          
          - Windows 10/11 (64bit)
          - DirectX 12, Vulkan, またはOpenGL ES対応GPU
          
          ### インストール
          
          1. ZIPファイルをダウンロード
          2. 任意のフォルダに展開
          3. `rs_fast_image_viewer.exe` を実行
          
          ### 使用方法
          
          ```bash
          rs_fast_image_viewer.exe [画像ファイルまたはディレクトリ]
          ```
          
          ### 対応フォーマット
          
          - JPEG (.jpg, .jpeg)
          - PNG (.png)  
          - WebP (.webp)
          
          ### キーボードショートカット
          
          - `→` または `X`: 次の画像
          - `←` または `Z`: 前の画像
          - `Enter` または `Escape`: 終了
          
          ### 変更点
          
          リリースノートは [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) をご覧ください。
          
          ---
          
          **チェックサム:** SHA256ハッシュファイル（`.sha256`）でファイルの整合性を確認できます。
        draft: false
        prerelease: ${{ contains(needs.prepare.outputs.tag, 'alpha') || contains(needs.prepare.outputs.tag, 'beta') || contains(needs.prepare.outputs.tag, 'rc') }}
        token: ${{ secrets.GITHUB_TOKEN }}